### ISSUE TITLE
Multiple outputs from one visualizer

### ISSUE THREAD

**Issue by roboraptor** [CaiB/ColorChord.NET#12]
Hi, 

I'm having a little trouble with setting up outputs as I want but not sure if it is even possible.

I have 4 WLED fixtures 1 LED each. 
So I created 1 Visualizer for 4 LED and now I want to take cell by cell and assign it to different WLED Output.

I use original sample Visualizer
```
"Type": "Linear",
"Name": "SampleLinear",
"LEDCount": 4,
"IsCircular": true,
"FrameRate": 60,
"LightSiding": 1.0,
"SteadyBright": false,
"LEDFloor": 0.1,
"LEDLimit": 1.0,
"SaturationAmplifier": 1.6,
"Enable": true
```

And this is my (dont ask how) fully working WLED Output. (You can add it to documentation, seems usefull)
```
"Type": "PacketUDP",
"Name": "SampleUDP",
"VisualizerName": "SampleLinear",
"IP": "192.168.3.103",
"Port": 65506,
"LEDPattern": "GRB",
"PaddingFront": 2,
"PaddingBack": 0,
"PaddingContent": 2,
"Enable": true,
"MaxPacketLength": 768,
"ConstantPacketLength": true,
"Protocol": "TPM2.net",
"SizeX": 1,
"SizeY": 1
```

Is there any option for Output like
```
"LEDIndex": [ 1 - LEDCount ]
```
OR
```
"VisualizerOffset": [ 1 - LEDCount ]
```
Would be very usefull as I dont need all fixtures to be the same and also creating another visualizer with same effect does not help.

**Comment by roboraptor** [comment]
Like this :)
![image](https://user-images.githubusercontent.com/17791899/186654201-8ffcd15d-f08e-4e34-9a1d-b75702693e91.png)
(now I play with more different Visualizers but I would like to use only one)

**Comment by CaiB** [comment]
Hello,

I don’t believe this is currently possible. However, I can definitely see how it would be useful, so I’ll take a stab at implementing this, seems pretty simple. I’ll let you know once I have something ready to test.

Thanks for the suggestion!

**Comment by roboraptor** [comment]
Thank you very much!
That would be lovely ❤️ 
I want to use it for LED PAR Lights for stage and such. 🔴 🟢 🔵 🟡 
It really looks like good opportunity for AutoMode.  👍 
Let me know if you have any 📅 time plan for that.

**Comment by roboraptor** [comment]
It is sad there is no actual workaround for that because of the concept, every visualiser gets (mostly) the same things to output 😅

**Comment by CaiB** [comment]
Sounds awesome. I should be able to get this done in the next few days.
For such lighting systems, you may also be able to use the E1.31 output mode, however it currently has the same restrictions so won't work any better just yet.
I'd love to see a video of it running on there once we get it working!

**Comment by roboraptor** [comment]
I wanted to try E1.31 but TMP2 started to work for me first so I stuck with that. 
If you think it delivers better function or FPS we can definitely look into that.
Also count on me with some videos and how it works!

**Comment by roboraptor** [comment]
Quick Workaround Foud!
First lamp set as a DDP master and sending data to other lamps so first one *looks* like 3 LEDs srtip to CC.NET 

<sup>If you want to work on it for other outputs please do, for Me it now works as wanted so you can possibly close?<sup>

**Comment by CaiB** [comment]
OK, I added this functionality, could you give it a test when you have a chance?
Start by downloading the newest autobuild (172 or later)
Then, for each `PacketUDP` entry in the config file, add 2 properties: `"StartIndex"` and `"EndIndex"`. Set them as `0` and `1` respectively for the first `PacketUDP`, `1` and `2` for the second, `2` and `3` for the 3rd, etc.

**Comment by CaiB** [comment]
Also, regarding E1.31: It doesn't provide any better performance for CC.NET (in fact it's just a little bit worse), but it's a protocol that may be natively understood by your lighting equipment (It's pretty much DMX over Ethernet). If your lights can understand it natively, there's no need for intermediate hardware (WLED/ESP), which could help reduce latency and make your setup simpler. If your lights cannot use this protocol, then just stick with TPM2.NET.

**Comment by roboraptor** [comment]
I tried, and it works! ❤️
