### ISSUE TITLE
OpenGL Display to FullScreen

### ISSUE THREAD

**Issue by roboraptor** [CaiB/ColorChord.NET#13]
It would be nice to not only Maximalise the window but even to put it into FullScreen mode. 
Could use that with projectors and such :)

**Comment by CaiB** [comment]
Hello,

Thanks for checking out CC.NET!
I actually just implemented this not too long ago. If you’re using the newest autobuild versions, you can enter and exit fullscreen mode with F or F11.
Let me know if that works for you :)

**Comment by roboraptor** [comment]
F#@& me dead! You are awesome!
It works flawlessly.  👍
