### ISSUE TITLE
Enable on every output

### ISSUE THREAD

**Issue by roboraptor** [CaiB/ColorChord.NET#16]
From what I got, It looks like there is Enable function only for PacketUDP.
Is it possible to add Enable for every output? 
like DisplayOpenGL and MemoryMap

**Comment by CaiB** [comment]
Enable makes sense on MemoryMap, but I'm not sure what it'd do for DisplayOpenGL. Open/close the window completely? Pause the view?

**Comment by roboraptor** [comment]
I find it a bit flustrating decision. 
Maybe we are getting into what enable really should be.

Enable, from your code, for me, looks like if it is false, the whole block of code gets skipped.
As now we are testing the Controller, it would be useful that i don't need to remove my code for OpenGL and simply could just "false" it.
(I know it is just dev bug which gets removed later)
[This would close the window because there is no output which says have the window]

But when I start to think about what should be controlled through the Controller, it is not this kind of Enable.
It should be more like having a fader over output that you can adjust and when it is on zero, it stops to send updates (so different program can). And that is certainly not skipping a block of code.
[This would pause the colors and decay to black and stopped broadcast]

I'm trying to think it through and also creating some visuals in Figma for the controller fronted so I can better tell what is useful (for me) and what I really mean.

**Comment by CaiB** [comment]
In the case of PacketUDP, when `Enable` is toggled to `false`, the output stops sending packets to the target (and skips all of the code to minimize resource usage during this time). The same will be true for `MemoryMap`, where writing to the mapped file would simply be skipped when disabled. This works well, as "sending data or not" maps very naturally onto a boolean setting.

For the case where you want to enable or disable sections in the config easily, like you wanted to now for testing, it would make sense to have disabling a `DisplayOpenGL` cause it to close (or never open in the first place) the window and not process any data. However, closing and re-opening the window is quite resource-intensive, and I'm not sure why this would be something a person wants to do at runtime. I may simply not make that controllable, only configurable, at least for now.

**Comment by roboraptor** [comment]
With your input, you are totally right, make it just configurable, not controllable.
You are the best
❤️

**Comment by CaiB** [comment]
As of autobuild 187, `DisplayOpenGL` has a configurable (but not controllable) `Enable` option. When disabled in the config, the window will not open and data will not be processed.
