### ISSUE TITLE
nothing happens when I execute the program

### ISSUE THREAD

**Issue by ghost** [CaiB/ColorChord.NET#19]
I've downloaded the latest release, and I'm on Windows 10 22H2. The program, when opened, briefly shows a window and then disappears. It also didn't create the config.json file. I tried manually creating a config.json with the sample configs, with no avail. Not sure what is wrong.

**Comment by CaiB** [comment]
Hi, thanks for giving it a try!

It sounds like the issue might be that you don't have the needed version of .NET installed.
You can check by going to Settings -> Apps, and searching for ".NET".

Currently the requirement is .NET 6.0 or newer, but I'd recommend installing 7.

If that doesn't help, could you try running it from the console? In the folder where the exe is, Shift+Right Click (not on any file), and select Open Terminal or Open PowerShell window, then just entering this:
`.\ColorChord.NET.exe`
Then press enter, and let me know what it outputs.

**Comment by ghost** [comment]
I had .NET 6.0.15, so I installed the 7.0, but it also didn't open. I tried the powershell thing and, weirdly, it asked me to download 5.0 (https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=5.0.0&arch=x64&rid=win10-x64). Apparently it requires it to run

**Comment by CaiB** [comment]
Oh, please try the newest autobuild instead of the release. The release is embarrassingly old at this point.

**Comment by ghost** [comment]
It was returning some "failed to initialize" errors but it was my fault as I was running WASAPI on exclusive mode. It seems to be working now, but I can only see some coloured blocks. like this:

![image](https://github.com/CaiB/ColorChord.NET/assets/107224222/35879b5c-9b25-42c0-a642-5b8b32999a8f)

**Comment by ghost** [comment]
oh nvm, this is how it is supposed to look

**Comment by ghost** [comment]
well, seems to be working alright now, the only issue I can find is the fact it freezes whenever you move or resize the window

**Comment by ghost** [comment]
oh and I used the latest autobuild

**Comment by CaiB** [comment]
Yep, that's the simple default one. There are other display modes you can play around with, some of them are listed here: https://www.colorchord.net/docs/outputs/displayopengl/

Yeah, the freezing during move/resize happens here too. I should look into that sometime...
