### ISSUE TITLE
Add traditional FFT-based spectrum for NoteFinder

### ISSUE THREAD

**Issue by TF3RDL** [CaiB/ColorChord.NET#22]
Out of curiosity, I've just want to have FFT-based one [like this one](https://codepen.io/TF3RDL/pen/poQJwRW) where at higher frequencies, multiple FFT bins within the band's low and high boundaries are summed into one whereas at lower frequencies, FFT bins are interpolated using Lanczos (windowed sinc) to make up for lesser dense data for lower frequencies in log frequency scale since FFT are linearly-spaced, for the NoteFinder for the sake of comparison with other techniques like biquad bandpass filter banks that I've seen on octave-band analyzers

**Comment by CaiB** [comment]
This is outside the scope of my current plans for CC.NET. You are of course welcome to fork it and implement these features yourself.
